### PR TITLE
Let users add arbitrary configuration to tests

### LINKED ISSUE #193: [Feature] Change build settings (`extra_config`) in UnitTests target too
Hi @gfontenot 

I wanted to change specific Build Settings in my Unit Tests target (namely remove `TEST_HOST` and `BUNDLE_LOADER` build settings to set empty values, so that my CI don't try to launch the simulator and fail, whereas I don't have any application test but only functional ones)

Using `extra_config` only changes Build Settings of the App Target. It would be great to have a `tests_extra_config` or something similar for the Unit Tests Target too.

### PR DESCRIPTION
**Pull request by gfontenot**
This adds the `extra_test_config` key to the `liftoffrc`. This key acts 
similarly to the `extra_config` key, but adds arbitrary configuration to the
test target. If more than one test target exists, the user will be given the
chance to select the target they would like to modify.

Fixes #193

### CODE REVIEW

File: lib/liftoff/xcodeproj_helper.rb [hunk 1]
```diff
@@ -53,18 +53,20 @@ def add_script_phases(scripts)
...
-      if extra_config
-        extra_config.each do |name, settings|
-          if name.downcase == "all"
-            object = target
-          else
-            object = target.build_settings(name)
-          end
+    def perform_extra_config(app_config, test_config)
+      [app_config, test_config].each do |config|
+        if config
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: You could do `.compact.each` to remove this `if` statement. `.compact` removes `nil`s.

File: lib/liftoff/xcodeproj_helper.rb [hunk 2]
```diff
@@ -53,18 +53,20 @@ def add_script_phases(scripts)
...
+              object = target
+            else
+              object = target.build_settings(name)
+            end
 
-          if object
-            settings.each do |key, value|
-              object[key] = value
+            if object
+              settings.each do |key, value|
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: Is `settings` a hash? Can you just copy it over like `object = settings.clone`?

Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: It is, but I can't overwrite `object` since there are other things in there.. I _might_ be able to `merge!` that sucker though.

File: lib/liftoff/xcodeproj_helper.rb (hunk 1 above)
Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: How functional!

File: lib/liftoff/xcodeproj_helper.rb [hunk 3]
```diff
@@ -81,10 +83,18 @@ def target
...
 
+    def test_target
+      @test_target ||= ObjectPicker.choose_item('test target', available_test_targets)
+    end
+
     def available_targets
       xcode_project.targets.to_a.reject { |t| t.name.end_with?('Tests') }
     end
 
+    def available_targets
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: This redefines the `available_targets` method. Should this be `available_test_targets` instead?

File: lib/liftoff/xcodeproj_helper.rb [hunk 4]
```diff
@@ -81,10 +83,18 @@ def target
...
+      xcode_project.targets.to_a.select { |t| t.name.end_with?('Tests') }
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: Is it worth extracting `xcode_project.targets.to_a`, since you use it twice? Maybe call it `targets`?

File: lib/liftoff/xcodeproj_helper.rb (hunk 2 above)
Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: oh right `object` isn't a hash. That's fun.

Comment (jferris) [inline lib/liftoff/xcodeproj_helper.rb]: It sounds like maybe you want to make an object that wraps this one and acts more like a `Hash`?

Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: so if `object` is a specific build setting, then it _is_ a hash. But if it's the target itself, it isn't a hash. This is probably actually a mess I got myself into by trying to simplify this code.

File: lib/liftoff/xcodeproj_helper.rb [hunk 5]
```diff
@@ -78,11 +78,23 @@ def save
...
     def target
-      @target ||= ObjectPicker.choose_item('target', available_targets)
+      @target ||= ObjectPicker.choose_item('target', application_targets)
+    end
+
+    def test_target
+      @test_target ||= ObjectPicker.choose_item('test target', test_targets)
+    end
+
+    def all_targets
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: Should this be lower down in the file, so that higher-level methods (that use this one) are above it? I like to go higher-to-lower as I read down a file.

File: lib/liftoff/xcodeproj_helper.rb [hunk 6]
```diff
@@ -53,18 +53,18 @@ def add_script_phases(scripts)
...
-    def perform_extra_config(extra_config)
-      if extra_config
-        extra_config.each do |name, settings|
-          if name.downcase == "all"
-            object = target
-          else
-            object = target.build_settings(name)
-          end
+    def perform_extra_config(app_config, test_config)
+      {app_config => target, test_config => test_target}.each do |config, t|
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: What about renaming `t` to `target`, and renaming the `target` method below to something a little more descriptive?

File: lib/liftoff/xcodeproj_helper.rb (hunk 5 above)
Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: yep, good call. Done.

File: lib/liftoff/xcodeproj_helper.rb (hunk 6 above)
Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: Done

**Comment by gfontenot** [comment]
@gabebw I'm going to merge this unless you had any other comments.

File: lib/liftoff/xcodeproj_helper.rb [hunk 7]
```diff
@@ -53,18 +53,18 @@ def add_script_phases(scripts)
...
-            object = target
-          else
-            object = target.build_settings(name)
-          end
+    def perform_extra_config(app_config, test_config)
+      {app_config => application_target, test_config => test_target}.each do |config, target|
+        if config
+          config.each do |name, settings|
+            if name.downcase == "all"
+              object = target
```
Comment (gabebw) [inline lib/liftoff/xcodeproj_helper.rb]: Should this now be `application_target`?

Comment (gfontenot) [inline lib/liftoff/xcodeproj_helper.rb]: Nope, it's whatever target we've associated with the config on line 56.

**Comment by gabebw** [comment]
:+1:

**Comment by gfontenot** [comment]
merged as a159489
